/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int max_swerve_lerp(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int max_swerve_lerp_alloc_mem(void);
int max_swerve_lerp_init_mem(int mem);
void max_swerve_lerp_free_mem(int mem);
int max_swerve_lerp_checkout(void);
void max_swerve_lerp_release(int mem);
void max_swerve_lerp_incref(void);
void max_swerve_lerp_decref(void);
casadi_int max_swerve_lerp_n_in(void);
casadi_int max_swerve_lerp_n_out(void);
casadi_real max_swerve_lerp_default_in(casadi_int i);
const char* max_swerve_lerp_name_in(casadi_int i);
const char* max_swerve_lerp_name_out(casadi_int i);
const casadi_int* max_swerve_lerp_sparsity_in(casadi_int i);
const casadi_int* max_swerve_lerp_sparsity_out(casadi_int i);
int max_swerve_lerp_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int max_swerve_lerp_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define max_swerve_lerp_SZ_ARG 22
#define max_swerve_lerp_SZ_RES 20
#define max_swerve_lerp_SZ_IW 50
#define max_swerve_lerp_SZ_W 402
#ifdef __cplusplus
} /* extern "C" */
#endif
